-- 0017: dejar que el cliente lea las columnas que 0014 agregó.
--
-- La 0014 sumó key_figure, key_figure_label y sources a `reports`, pero nadie
-- tocó los grants — y en esta tabla eso no es un detalle. La 0009 revocó el
-- SELECT a nivel de tabla y lo volvió a conceder sobre una LISTA FIJA de
-- columnas, para poder esconder `file_path` (RLS filtra filas, no columnas:
-- ocultar una columna solo se hace con grants). Consecuencia: cualquier
-- columna nueva nace SIN permiso de lectura para anon/authenticated, y no hay
-- ningún aviso — un `select key_figure` desde el navegador devuelve
-- "permission denied for table reports", que ni siquiera nombra la columna.
--
-- Cómo se nos pasó, para que no se repita: las tareas que agregaron y llenaron
-- estas columnas las verificaron con `supabase db query`, que corre con rol
-- privilegiado y ve todo. Comprobar una columna destinada al navegador usando
-- una conexión privilegiada no prueba nada sobre el navegador. Lo detectó el
-- primer script que las leyó con la clave publishable.
--
-- `file_path` NO se concede acá, a propósito: sigue oculto. La descarga la
-- resuelve la Edge Function con la clave de servicio, que sí lo lee. Si algún
-- día agregas otra columna pública a `reports`, agrégala también a este grant.

grant select (key_figure, key_figure_label, sources) on public.reports to anon, authenticated;
